apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  labels:
    app.kubernetes.io/name: o2
    app.kubernetes.io/managed-by: kustomize
  name: olsconfig-sample
spec:
  # TODO(user): Add fields here
